"""Unification of the models.

Revision ID: 1cca158666c9
Revises: 40114ff8d783
Create Date: 2025-02-05 16:21:19.119354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cca158666c9'
down_revision = '40114ff8d783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    with op.batch_alter_table('affected', schema=None) as batch_op:
        batch_op.alter_column('needs',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('authorities', schema=None) as batch_op:
        batch_op.alter_column('approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['phone'])

    with op.batch_alter_table('charity_campaign', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('coordinates', schema=None) as batch_op:
        batch_op.alter_column('x',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('y',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    with op.batch_alter_table('danger_area', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('coordinates',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    with op.batch_alter_table('donation_item', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('donation_money', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('donation_type', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['type'])

    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['phone_number'])
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('item_stock', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('coordinates_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('type_of_poi',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('relief_area', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('coordinates',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('affected_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('donation_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('charity_campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('charity_campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('volunteer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('evaluation_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('evaluation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('volunteer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('charity_campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('charity_campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('donation_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('affected_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('relief_area', schema=None) as batch_op:
        batch_op.alter_column('coordinates',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.alter_column('type_of_poi',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('coordinates_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('item_stock', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('donation_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('donation_money', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('donation_item', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('danger_area', schema=None) as batch_op:
        batch_op.alter_column('coordinates',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('coordinates', schema=None) as batch_op:
        batch_op.alter_column('y',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('x',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    with op.batch_alter_table('charity_campaign', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('authorities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('affected', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('needs',
               existing_type=sa.TEXT(),
               nullable=True)

    op.create_table('message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name='message_receiver_id_fkey'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='message_sender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='message_pkey')
    )
    # ### end Alembic commands ###
