"""Unification of the models.

Revision ID: 45ab8b7b35a8
Revises: 1cca158666c9
Create Date: 2025-02-05 16:23:13.337292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ab8b7b35a8'
down_revision = '1cca158666c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('evaluation_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('evaluation_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
