"""Notification type

Revision ID: e8b721c2ae9a
Revises: 45ab8b7b35a8
Create Date: 2025-02-06 11:42:43.521708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b721c2ae9a'
down_revision = '45ab8b7b35a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('MESSAGE', 'REQUEST', 'TASK', 'DONATION', name='notificationtype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
